### ISSUE TITLE
The page not found in this link

### ISSUE THREAD

**Issue by lindexi** [MicrosoftDocs/windows-driver-docs.zh-cn#2]
https://www.usb.org/developers/hidpage/HID1_11.pdf page not found

https://www.usb.org/developers/hidpage/Hut1_12v2.pdf page not found

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ba1cf2aa-effc-7b31-2540-470205e840f3
* Version Independent ID: 8b1f865f-a19e-0e96-1c1f-5c0206afe797
* Content: [基于 USB 的 HID 的资源 - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/hid/reference-and-additional-details)
* Content Source: [windows-driver-docs-pr/hid/reference-and-additional-details.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/hid/reference-and-additional-details.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by srvbpigh** [comment]
Hello, @lindexi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @lindexi

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windows-driver-docs/issues/1770

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
