### ISSUE TITLE
Question about MBIM structure

### ISSUE THREAD

**Issue by XXXXzzzz000** [MicrosoftDocs/windows-driver-docs.zh-cn#7]
where can i got the structure define of MBIM_MS_SET_UICC_TERMINAL_CAPABILITY?
I only can understand : this payload is a struct array, but i can't get any information of this struct array
Thanks.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c17a35ca-60a6-fd9f-e171-8413f8ea4604
* Version Independent ID: 7516b9db-e539-19d7-9be6-1140f6141404
* Content: [MB 低级别 UICC 访问 - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/network/mb-low-level-uicc-access)
* Content Source: [windows-driver-docs-pr/network/mb-low-level-uicc-access.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/network/mb-low-level-uicc-access.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by srvbpigh** [comment]
Hello, @XXXXzzzz000
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @XXXXzzzz000

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windows-driver-docs/issues/1900

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
