### ISSUE TITLE
download WDK Insider Preview can not open .

### ISSUE THREAD

**Issue by 751797916** [MicrosoftDocs/windows-driver-docs.zh-cn#9]
this page show " The URL may be misspelled or the page you're looking for is no longer available."

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3f5d6d55-cb35-6b9e-f8ca-e75f70826dc3
* Version Independent ID: 1d913516-b1e0-e872-c337-e30ed5dffce8
* Content: [以前的 WDK 版本和其他下载 - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/other-wdk-downloads#feedback)
* Content Source: [windows-driver-docs-pr/other-wdk-downloads.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/other-wdk-downloads.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by srvbpigh** [comment]
Hello, @751797916
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @<contributor's GITHUB name>,
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. 

You are refering to this link, right?
![imagen](https://user-images.githubusercontent.com/26746247/71482856-89223000-27e3-11ea-92c6-13f49f0eaee2.png)
When I click on it it takes me to an en-us page and the message I get is "To access this page, you need to be a member of the Windows Insider program."

If this is not correct, please provide further repro steps and screenshots so we can help you.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @751797916 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
